# Set to true to use lowercase keywords instead of uppercase.
lowercaseKeywords: false
connections:
  - alias: individual_mysql
    driver: mysql
    proto: tcp
    user: root
    passwd: password
    host: 0.0.0.0
    port: 3306
    params:
      autocommit: "true"
      tls: skip-verify
